@echo off
setlocal

rem Function to execute a command and log errors
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split1\val --model vgg16 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_vgg16_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_vgg16_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split2\val --model vgg16 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_vgg16_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_vgg16_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split3\val --model vgg16 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_vgg16_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_vgg16_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split4\val --model vgg16 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_vgg16_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_vgg16_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split5\val --model vgg16 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_vgg16_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_vgg16_SGD

python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split1\val --model resnet50 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_resnet50_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_resnet50_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split2\val --model resnet50 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_resnet50_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_resnet50_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split3\val --model resnet50 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_resnet50_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_resnet50_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split4\val --model resnet50 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_resnet50_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_resnet50_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split5\val --model resnet50 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_resnet50_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_resnet50_SGD

python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split1\val --model googlenet --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_googlenet_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_googlenet_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split2\val --model googlenet --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_googlenet_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_googlenet_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split3\val --model googlenet --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_googlenet_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_googlenet_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split4\val --model googlenet --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_googlenet_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_googlenet_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split5\val --model googlenet --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_googlenet_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_googlenet_SGD

python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split1\val --model mobilenetv2 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_mobilenetv2_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split1_mobilenetv2_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split2\val --model mobilenetv2 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_mobilenetv2_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split2_mobilenetv2_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split3\val --model mobilenetv2 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_mobilenetv2_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split3_mobilenetv2_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split4\val --model mobilenetv2 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_mobilenetv2_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split4_mobilenetv2_SGD
python inference.py --data_root C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\softmax\split5\val --model mobilenetv2 --model_path "C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_mobilenetv2_SGD\model.pth" --output_dir C:\Users\JJJ\my\data\.images\FAST\rawdata\RUQ\classification\result\softmax\split5_mobilenetv2_SGD
